[package]
name = "srco2"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14.1"
env_logger = "0.6.2"
git2 = "0.10.0"
log = "0.4.8"
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["tera_templates"] }
ron = "0.5.1"
serde = { version = "1.0.99", features = ["derive"] }
snafu = "0.5.0"
